DECLARE @N1 INT, @N2 INT, @N3 INT
DECLARE @THE_GREATEST INT;

SET @N1 = 60 * RAND();
SET @N2 = 60 * RAND();
SET @N3 = 60 * RAND();

/*SELECT @THE_GREATEST = max(Name)
FROM (SELECT @N1 
      UNION all
	  SELECT @N2
	  UNION all
	  SELECT @N3) T(Name)
*/
IF @N1 > @N2 AND @N1 > @N3
SET @THE_GREATEST = @N1

IF @N2 > @N1 AND @N2 > @N3
SET @THE_GREATEST = @N2

IF @N3 > @N1 AND @N1 > @N2
SET @THE_GREATEST = @N2

PRINT @N1;
PRINT @N2;
PRINT @N3;
PRINT 'The greatest = ' + CAST(@THE_GREATEST AS VARCHAR(2));