DECLARE @N1 INT, @N2 INT, @N3 INT
DECLARE @THE_GREATEST INT;

SET @N1 = 60 * RAND();
SET @N2 = 60 * RAND();
SET @N3 = 60 * RAND();

SET @THE_GREATEST = CASE 
WHEN (@N1 > @N2 AND @N1 > @N3) THEN @N1
WHEN (@N2 > @N1 AND @N2 > @N3) THEN @N2
ELSE @N3
END

PRINT @N1;
PRINT @N2;
PRINT @N3;

PRINT 'The greatest = ' + CAST(@THE_GREATEST AS VARCHAR(2));